SET search_path TO tmdb, public;

-- =========================
-- Basis-Lookup-Tabellen
-- =========================

CREATE TABLE country (
                         id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         iso_3166_1         VARCHAR(2)  NOT NULL,
                         name               TEXT        NOT NULL,
                         CONSTRAINT uq_country_code UNIQUE (iso_3166_1),
                         CONSTRAINT uq_country_name UNIQUE (name)
);

CREATE TABLE language (
                          id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          iso_639_1          VARCHAR(2)  NOT NULL,
                          english_name       TEXT,
                          name               TEXT,
                          CONSTRAINT uq_language_code UNIQUE (iso_639_1)
);

CREATE TABLE genre (
                       id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       tmdb_id            INTEGER     NOT NULL,
                       name               TEXT        NOT NULL,
                       CONSTRAINT uq_genre_tmdb UNIQUE (tmdb_id),
                       CONSTRAINT uq_genre_name UNIQUE (name)
);

CREATE TABLE department (
                            id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name               TEXT NOT NULL,
                            CONSTRAINT uq_department_name UNIQUE (name)
);

CREATE TABLE job (
                     id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     department_id      INTEGER NOT NULL REFERENCES department(id) ON DELETE RESTRICT,
                     name               TEXT    NOT NULL,
                     CONSTRAINT uq_job_dept_name UNIQUE (department_id, name)
);
CREATE INDEX idx_job_department ON job(department_id);

-- =========================
-- Personen (Actors etc.)
-- =========================

CREATE TABLE person (
                        id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        tmdb_id                INTEGER     NOT NULL,
                        imdb_id                TEXT,
                        name                   TEXT        NOT NULL,
                        gender                 INTEGER,
                        known_for_department   TEXT,
                        biography              TEXT,
                        birthday               DATE,
                        deathday               DATE,
                        place_of_birth         TEXT,
                        homepage               TEXT,
                        adult                  BOOLEAN,
                        popularity             NUMERIC(10,3),
                        CONSTRAINT uq_person_tmdb UNIQUE (tmdb_id),
                        CONSTRAINT uq_person_imdb UNIQUE (imdb_id)
);

CREATE TABLE person_aka (
                            id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            person_id  INTEGER NOT NULL REFERENCES person(id) ON DELETE CASCADE,
                            aka_name   TEXT    NOT NULL
);
CREATE INDEX idx_person_aka_person ON person_aka(person_id);

-- =========================
-- Filme
-- =========================

CREATE TABLE movie (
                       id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       tmdb_id              INTEGER     NOT NULL,
                       imdb_id              TEXT,
                       title                TEXT,
                       original_title       TEXT,
                       original_language    VARCHAR(10),
                       adult                BOOLEAN,
                       video                BOOLEAN,
                       status               TEXT,
                       release_date         DATE,
                       budget               INTEGER,
                       revenue              BIGINT,
                       runtime              INTEGER,
                       homepage             TEXT,
                       overview             TEXT,
                       poster_path          TEXT,
                       popularity           NUMERIC(12,3),
                       vote_average         NUMERIC(4,2),
                       vote_count           INTEGER,
                       tagline              TEXT,
                       CONSTRAINT uq_movie_tmdb UNIQUE (tmdb_id),
                       CONSTRAINT uq_movie_imdb UNIQUE (imdb_id)
);
CREATE INDEX idx_movie_release_date ON movie(release_date);

CREATE TABLE movie_title (
                             id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             movie_id      INTEGER NOT NULL REFERENCES movie(id) ON DELETE CASCADE,
                             iso_3166_1    VARCHAR(2) NOT NULL,
                             title         TEXT,
                             type          TEXT,
                             CONSTRAINT fk_movie_title_country FOREIGN KEY (iso_3166_1) REFERENCES country(iso_3166_1)
);
CREATE INDEX idx_movie_title_movie   ON movie_title(movie_id);
CREATE INDEX idx_movie_title_country ON movie_title(iso_3166_1);

CREATE TABLE movie_genre (
                             id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             movie_id   INTEGER NOT NULL REFERENCES movie(id) ON DELETE CASCADE,
                             genre_id   INTEGER NOT NULL REFERENCES genre(id) ON DELETE RESTRICT,
                             CONSTRAINT uq_movie_genre UNIQUE (movie_id, genre_id)
);
CREATE INDEX idx_movie_genre_movie ON movie_genre(movie_id);
CREATE INDEX idx_movie_genre_genre ON movie_genre(genre_id);

CREATE TABLE movie_spoken_language (
                                       id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       movie_id      INTEGER NOT NULL REFERENCES movie(id) ON DELETE CASCADE,
                                       iso_639_1     VARCHAR(2) NOT NULL,
                                       name          TEXT,
                                       english_name  TEXT,
                                       CONSTRAINT fk_msl_lang FOREIGN KEY (iso_639_1) REFERENCES language(iso_639_1),
                                       CONSTRAINT uq_msl UNIQUE (movie_id, iso_639_1)
);
CREATE INDEX idx_msl_movie ON movie_spoken_language(movie_id);
CREATE INDEX idx_msl_lang  ON movie_spoken_language(iso_639_1);

CREATE TABLE movie_production_country (
                                          id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          movie_id      INTEGER NOT NULL REFERENCES movie(id) ON DELETE CASCADE,
                                          iso_3166_1    VARCHAR(2) NOT NULL,
                                          name          TEXT,
                                          CONSTRAINT fk_mpc_country FOREIGN KEY (iso_3166_1) REFERENCES country(iso_3166_1),
                                          CONSTRAINT uq_mpc UNIQUE (movie_id, iso_3166_1)
);
CREATE INDEX idx_mpc_movie   ON movie_production_country(movie_id);
CREATE INDEX idx_mpc_country ON movie_production_country(iso_3166_1);

CREATE TABLE movie_origin_country (
                                      id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      movie_id      INTEGER NOT NULL REFERENCES movie(id) ON DELETE CASCADE,
                                      iso_3166_1    VARCHAR(2) NOT NULL,
                                      CONSTRAINT fk_moc_country FOREIGN KEY (iso_3166_1) REFERENCES country(iso_3166_1),
                                      CONSTRAINT uq_moc UNIQUE (movie_id, iso_3166_1)
);
CREATE INDEX idx_moc_movie   ON movie_origin_country(movie_id);
CREATE INDEX idx_moc_country ON movie_origin_country(iso_3166_1);

-- =========================
-- Produktionsfirmen
-- =========================

CREATE TABLE production_company (
                                    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    tmdb_id         INTEGER     NOT NULL,
                                    name            TEXT        NOT NULL,
                                    logo_path       TEXT,
                                    origin_country  VARCHAR(2),
                                    CONSTRAINT uq_pc_tmdb UNIQUE (tmdb_id),
                                    CONSTRAINT fk_pc_country FOREIGN KEY (origin_country) REFERENCES country(iso_3166_1)
);
CREATE INDEX idx_pc_origin_country ON production_company(origin_country);

CREATE TABLE movie_production_company (
                                          id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          movie_id                INTEGER NOT NULL REFERENCES movie(id) ON DELETE CASCADE,
                                          production_company_id   INTEGER NOT NULL REFERENCES production_company(id) ON DELETE RESTRICT,
                                          CONSTRAINT uq_mpc_company UNIQUE (movie_id, production_company_id)
);
CREATE INDEX idx_mpc_company_movie  ON movie_production_company(movie_id);
CREATE INDEX idx_mpc_company_pc     ON movie_production_company(production_company_id);

-- =========================
-- Credits (Besetzungen/Jobs)
-- =========================

CREATE TABLE credits (
                         id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         movie_id  INTEGER NOT NULL REFERENCES movie(id)   ON DELETE CASCADE,
                         actor_id  INTEGER NOT NULL REFERENCES person(id)  ON DELETE RESTRICT,
                         job_id    INTEGER NOT NULL REFERENCES job(id)     ON DELETE RESTRICT,
                         CONSTRAINT uq_credits_movie_actor_job UNIQUE (movie_id, actor_id, job_id)
);
CREATE INDEX idx_credits_movie ON credits (movie_id);
CREATE INDEX idx_credits_actor ON credits (actor_id);
CREATE INDEX idx_credits_job   ON credits (job_id);

-- Optionale Kommentare
COMMENT ON TABLE movie IS 'Filme (TMDB/IMDB Metadaten)';
COMMENT ON COLUMN movie.tmdb_id IS 'Externer Schlüssel auf TMDB';
COMMENT ON TABLE credits IS 'Zuweisung von Personen zu Filmen und Jobs';
