-- =========================
-- Basis-Lookup-Tabellen
-- =========================

CREATE TABLE country
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso_3166_1 CHAR(2) UNIQUE NOT NULL,
    name       TEXT UNIQUE    NOT NULL
);

CREATE TABLE language
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iso_639_1    CHAR(2) UNIQUE NOT NULL,
    english_name TEXT,
    name         TEXT
);

CREATE TABLE genre
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id INTEGER UNIQUE NOT NULL,
    name    TEXT UNIQUE    NOT NULL
);

CREATE TABLE department
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE job
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER NOT NULL REFERENCES department (id) ON DELETE RESTRICT,
    name          TEXT    NOT NULL,
    CONSTRAINT uq_job_dept UNIQUE (department_id, name)
);

-- =========================
-- Personen
-- =========================

CREATE TABLE person
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id              INTEGER UNIQUE NOT NULL,
    imdb_id              TEXT UNIQUE,
    name                 TEXT           NOT NULL,
    gender               INTEGER,
    known_for_department INTEGER REFERENCES department (id),
    biography            TEXT,
    birthday             DATE,
    deathday             DATE,
    place_of_birth       TEXT,
    homepage             TEXT,
    adult                BOOLEAN,
    popularity           NUMERIC(10, 3)
);

CREATE TABLE person_alias
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INTEGER NOT NULL REFERENCES person (id) ON DELETE CASCADE,
    alias     TEXT    NOT NULL
);

-- =========================
-- Filme
-- =========================

CREATE TABLE movie
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id           INTEGER UNIQUE NOT NULL,
    imdb_id           TEXT UNIQUE,
    title             TEXT,
    original_title    TEXT,
    original_language CHAR(2) REFERENCES language (iso_639_1),
    adult             BOOLEAN,
    video             BOOLEAN,
    status            TEXT,
    release_date      DATE,
    budget            INTEGER,
    revenue           BIGINT,
    runtime           INTEGER,
    homepage          TEXT,
    overview          TEXT,
    popularity        NUMERIC(12, 3),
    vote_average      NUMERIC(4, 2),
    vote_count        INTEGER,
    tagline           TEXT
);

CREATE TABLE movie_title
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id   INTEGER NOT NULL REFERENCES movie (id) ON DELETE CASCADE,
    iso_3166_1 CHAR(2) NOT NULL REFERENCES country (iso_3166_1),
    title      TEXT,
    type       TEXT
);

CREATE TABLE movie_genre
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id INTEGER NOT NULL REFERENCES movie (id) ON DELETE CASCADE,
    genre_id INTEGER NOT NULL REFERENCES genre (id) ON DELETE RESTRICT,
    CONSTRAINT uq_movie_genre UNIQUE (movie_id, genre_id)
);

CREATE TABLE movie_spoken_language
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id  INTEGER NOT NULL REFERENCES movie (id) ON DELETE CASCADE,
    iso_639_1 CHAR(2) NOT NULL REFERENCES language (iso_639_1),
    CONSTRAINT uq_msl UNIQUE (movie_id, iso_639_1)
);

CREATE TABLE country_type
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        TEXT NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE movie_country
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id        INTEGER NOT NULL REFERENCES movie (id) ON DELETE CASCADE,
    iso_3166_1      CHAR(2) NOT NULL REFERENCES country (iso_3166_1),
    country_type_id INTEGER NOT NULL REFERENCES country_type (id) ON DELETE RESTRICT,
    CONSTRAINT uq_movie_country UNIQUE (movie_id, iso_3166_1, country_type_id)
);

-- =========================
-- Produktionsfirmen
-- =========================

CREATE TABLE production_company
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id        INTEGER UNIQUE NOT NULL,
    name           TEXT           NOT NULL,
    origin_country CHAR(2) REFERENCES country (iso_3166_1)
);

CREATE TABLE movie_production_company
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id              INTEGER NOT NULL REFERENCES movie (id) ON DELETE CASCADE,
    production_company_id INTEGER NOT NULL REFERENCES production_company (id) ON DELETE RESTRICT,
    CONSTRAINT uq_mpc_company UNIQUE (movie_id, production_company_id)
);

-- =========================
-- Credits (Platzhalter; wird später befüllt)
-- =========================

CREATE TABLE movie_cast
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id       INTEGER NOT NULL REFERENCES movie (id) ON DELETE CASCADE,
    person_id      INTEGER NOT NULL REFERENCES person (id) ON DELETE RESTRICT,
    character_name TEXT,
    cast_order     INTEGER,
    CONSTRAINT uq_movie_cast UNIQUE (movie_id, person_id, character_name)
);

CREATE TABLE movie_crew
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id  INTEGER NOT NULL REFERENCES movie (id) ON DELETE CASCADE,
    person_id INTEGER NOT NULL REFERENCES person (id) ON DELETE RESTRICT,
    job_id    INTEGER NOT NULL REFERENCES job (id) ON DELETE RESTRICT,
    CONSTRAINT uq_movie_crew UNIQUE (movie_id, person_id, job_id)
);

-- =========================
-- Watch Provider (Platzhalter; später)
-- =========================

CREATE TABLE watch_provider
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id          INTEGER NOT NULL,
    name             TEXT    NOT NULL,
    logo_path        TEXT,
    display_priority INTEGER,
    region           CHAR(2) REFERENCES country (iso_3166_1),
    CONSTRAINT uq_watch_provider_tmdb UNIQUE (tmdb_id, region)
);

CREATE TABLE movie_watch_provider
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id    INTEGER NOT NULL REFERENCES movie (id) ON DELETE CASCADE,
    provider_id INTEGER NOT NULL REFERENCES watch_provider (id) ON DELETE RESTRICT,
    type        TEXT CHECK (type IN ('flatrate', 'buy', 'rent', 'ads', 'free')),
    link        TEXT,
    CONSTRAINT uq_movie_provider UNIQUE (movie_id, provider_id, type)
);
